"""
player_data.py — Per-team structured data for WC 2026 factor engine.

Four categories:
  1. PLAYER PERFORMANCE  — key XI, current injuries/suspensions, player form ratings
  2. COACH STRATEGY      — coach name, formation, pressing intensity, set-piece threat
  3. COUNTER FACTORS     — tactical style profile (used for matchup analysis)
  4. POLITICAL/MORALE    — travel distance, squad morale, political context, unity

All fields are as of WC 2026 start (June 2026). Injuries updated manually or via
live_updater when martj42 repo covers lineup news.
"""

from __future__ import annotations

# ── Tactical style codes (for counter-strategy matchup logic) ─────────────────
# Used by factor_engine.py to determine tactical advantages
STYLE_CODES = {
    "high-press":     "HP",   # high-press wins vs possession, struggles vs counter
    "tiki-taka":      "TT",   # possession-heavy, beaten by deep blocks + counter
    "possession":     "PO",   # possession, beaten by disciplined counter
    "counter-attack": "CA",   # effective vs possession teams, beaten by physical press
    "attacking":      "AT",   # direct/high-risk, beaten by organised defence
    "defensive":      "DF",   # deep block, draws vs many, beaten by patient possession
}

# Counter-advantage matrix: ATTACKER style vs DEFENDER style → edge multiplier
# Positive = attacker gains edge, Negative = defender gains edge
# Scale: -0.15 to +0.15 (applied to xG)
COUNTER_MATRIX: dict[tuple[str,str], float] = {
    # High-press attacking a possession team → forces errors
    ("HP", "TT"): +0.10,
    ("HP", "PO"): +0.08,
    # Possession teams struggle vs organised counter
    ("TT", "CA"): -0.08,
    ("PO", "CA"): -0.06,
    # Counter-attack thrives against possession/tiki-taka
    ("CA", "TT"): +0.10,
    ("CA", "PO"): +0.07,
    # Attacking teams punish defensive sides IF quality gap > threshold
    ("AT", "DF"): +0.05,
    # Defensive blocks absorb pressure from attacking teams
    ("DF", "AT"): +0.04,
    # High-press vs counter — neutralises counter-threat
    ("HP", "CA"): +0.04,
    # Tiki-taka vs defensive — possession dominates but low yield
    ("TT", "DF"): +0.03,
}


# ── Per-team player/coach/political data ──────────────────────────────────────
# Note: injured/suspended lists = player names currently out.
# Set to [] if squad is fully fit.
PLAYER_DATA: dict[str, dict] = {

    # ══ Group A ══
    "United States": {
        "coach":              "Mauricio Pochettino",
        "formation":          "4-3-3",
        "key_xi":             ["Turner", "Dest", "Zimmermann", "Richards", "Robinson",
                               "McKennie", "Musah", "Adams", "Pulisic", "Reyna", "Balogun"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,   # +/- vs team_intel base (0 = no change)
        "pressing_intensity": 8.0,   # 0–10
        "set_piece_threat":   7.0,
        "counter_speed":      7.5,
        "aerial_strength":    6.5,
        "style_code":         "HP",
        "travel_distance_km": 0,     # host nation
        "squad_morale":       9.0,   # sky-high — home World Cup
        "political_context":  "Co-host nation. Massive crowd advantage, national pride moment.",
        "political_risk":     0,     # 0 = no issues, 10 = maximum disruption
    },
    "Panama": {
        "coach":              "Thomas Christiansen",
        "formation":          "4-4-2",
        "key_xi":             ["Mosquera", "Murillo", "Córdoba", "Davis", "Fajardo",
                               "Godoy", "Carrasquilla", "Escobar", "Cox"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 5.5,
        "set_piece_threat":   6.0,
        "counter_speed":      5.5,
        "aerial_strength":    6.0,
        "style_code":         "DF",
        "travel_distance_km": 2900,
        "squad_morale":       7.5,
        "political_context":  "First-ever WC. Extreme pride, highly motivated underdog.",
        "political_risk":     0,
    },
    "Honduras": {
        "coach":              "Reinaldo Rueda",
        "formation":          "4-2-3-1",
        "key_xi":             ["López", "Bengtson", "Elis", "Romo", "García"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 5.0,
        "set_piece_threat":   5.5,
        "counter_speed":      6.0,
        "aerial_strength":    6.5,
        "style_code":         "CA",
        "travel_distance_km": 3000,
        "squad_morale":       7.0,
        "political_context":  "Motivated by underdog status. No internal conflicts.",
        "political_risk":     0,
    },
    "Jamaica": {
        "coach":              "Heimir Hallgrímsson",
        "formation":          "4-3-3",
        "key_xi":             ["Blake", "Bailey", "Antonio", "Bell", "Morrison"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 6.5,
        "set_piece_threat":   6.0,
        "counter_speed":      8.0,   # Bailey is electric
        "aerial_strength":    7.0,
        "style_code":         "CA",
        "travel_distance_km": 2700,
        "squad_morale":       7.5,
        "political_context":  "Bailey is world-class but team is inconsistent. Positive camp.",
        "political_risk":     0,
    },

    # ══ Group B ══
    "Spain": {
        "coach":              "Luis de la Fuente",
        "formation":          "4-3-3",
        "key_xi":             ["Unai Simón", "Carvajal", "Le Normand", "Laporte", "Grimaldo",
                               "Pedri", "Rodri", "Fabian Ruiz", "Yamal", "Morata", "Williams"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   +0.5,  # Yamal peak season
        "pressing_intensity": 7.5,
        "set_piece_threat":   6.5,
        "counter_speed":      8.5,
        "aerial_strength":    6.0,
        "style_code":         "TT",
        "travel_distance_km": 7500,
        "squad_morale":       9.0,   # reigning EURO champions
        "political_context":  "Euro 2024 winners. Peak generation around Yamal and Pedri.",
        "political_risk":     0,
    },
    "Cabo Verde": {
        "coach":              "Bubista",
        "formation":          "4-3-3",
        "key_xi":             ["Vozinha", "Jamiro", "Garry Rodrigues", "Ryan Mendes"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 6.0,
        "set_piece_threat":   5.5,
        "counter_speed":      7.0,
        "aerial_strength":    6.5,
        "style_code":         "CA",
        "travel_distance_km": 7000,
        "squad_morale":       8.5,   # historic first WC
        "political_context":  "First WC ever. Small island nation — enormous national pride.",
        "political_risk":     0,
    },
    "Belgium": {
        "coach":              "Domenico Tedesco",
        "formation":          "3-4-3",
        "key_xi":             ["Casteels", "Alderweireld", "Vertonghen", "De Bruyne",
                               "Lukaku", "Doku", "Trossard", "Carrasco"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   -0.5,  # De Bruyne injury concerns, Lukaku fading
        "pressing_intensity": 7.0,
        "set_piece_threat":   7.5,
        "counter_speed":      7.5,
        "aerial_strength":    8.0,
        "style_code":         "AT",
        "travel_distance_km": 7200,
        "squad_morale":       7.0,   # golden generation aging
        "political_context":  "Last chance for this golden generation. High pressure.",
        "political_risk":     0,
    },
    "Egypt": {
        "coach":              "Hossam Hassan",
        "formation":          "4-2-3-1",
        "key_xi":             ["El-Shenawy", "Salah", "Trézéguet", "El-Nenny", "Marmoush"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   +0.5,  # Salah & Marmoush in excellent club form
        "pressing_intensity": 6.0,
        "set_piece_threat":   6.5,
        "counter_speed":      7.5,
        "aerial_strength":    6.5,
        "style_code":         "CA",
        "travel_distance_km": 9000,
        "squad_morale":       8.0,
        "political_context":  "Salah and Marmoush both in form. Dangerous dark horse.",
        "political_risk":     1,
    },

    # ══ Group C ══
    "Mexico": {
        "coach":              "Javier Aguirre",
        "formation":          "4-3-3",
        "key_xi":             ["Ochoa", "Gallardo", "Vega", "Sánchez", "Álvarez",
                               "Lozano", "Jiménez", "Corona"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 7.0,
        "set_piece_threat":   6.5,
        "counter_speed":      7.5,
        "aerial_strength":    6.5,
        "style_code":         "CA",
        "travel_distance_km": 0,     # co-host
        "squad_morale":       9.0,
        "political_context":  "Co-host. Enormous home pressure. El Tri must deliver.",
        "political_risk":     0,
    },
    "South Africa": {
        "coach":              "Hugo Broos",
        "formation":          "4-4-2",
        "key_xi":             ["Williams", "Tau", "Zwane", "Foster", "Modise"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 6.0,
        "set_piece_threat":   6.0,
        "counter_speed":      6.5,
        "aerial_strength":    6.5,
        "style_code":         "CA",
        "travel_distance_km": 13000,
        "squad_morale":       7.5,
        "political_context":  "Long journey from home. High motivation — first WC in years.",
        "political_risk":     1,
    },
    "Serbia": {
        "coach":              "Dragan Stojković",
        "formation":          "3-4-2-1",
        "key_xi":             ["Rajković", "Mitrović", "Vlahović", "Jović", "Milinković-Savić",
                               "Živković", "Lukić"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 7.5,
        "set_piece_threat":   8.0,   # Mitrović + Vlahović aerial threat
        "counter_speed":      6.5,
        "aerial_strength":    9.0,
        "style_code":         "AT",
        "travel_distance_km": 8000,
        "squad_morale":       8.0,
        "political_context":  "Physical and direct. Set-piece monsters. United squad.",
        "political_risk":     0,
    },
    "Costa Rica": {
        "coach":              "Gustavo Alfaro",
        "formation":          "4-1-4-1",
        "key_xi":             ["Navas", "Campbell", "Tejeda", "Calvo", "Fuller"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   -0.5,  # Navas ageing
        "pressing_intensity": 5.0,
        "set_piece_threat":   5.5,
        "counter_speed":      5.5,
        "aerial_strength":    6.0,
        "style_code":         "DF",
        "travel_distance_km": 3800,
        "squad_morale":       7.0,
        "political_context":  "Navas veteran leadership. Compact and hard to break down.",
        "political_risk":     0,
    },

    # ══ Group D ══
    "France": {
        "coach":              "Didier Deschamps",
        "formation":          "4-2-3-1",
        "key_xi":             ["Maignan", "Pavard", "Upamecano", "Saliba", "T.Hernández",
                               "Kanté", "Camavinga", "Griezmann", "Mbappé", "Thuram", "Dembélé"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   +0.5,  # Mbappé at Real Madrid
        "pressing_intensity": 7.5,
        "set_piece_threat":   7.5,
        "counter_speed":      9.5,   # Mbappé is fastest attacker in tournament
        "aerial_strength":    7.0,
        "style_code":         "CA",
        "travel_distance_km": 7500,
        "squad_morale":       8.5,
        "political_context":  "Internal tensions possible (Mbappé ego), but squad depth is unmatched.",
        "political_risk":     2,
    },
    "Argentina": {
        "coach":              "Lionel Scaloni",
        "formation":          "4-3-3",
        "key_xi":             ["E.Martínez", "Molina", "Romero", "Lisandro Martínez", "Acuña",
                               "De Paul", "Mac Allister", "Enzo Fernández", "Di María", "Lautaro", "Messi"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   -0.3,  # Messi age 38 but still influential
        "pressing_intensity": 7.0,
        "set_piece_threat":   7.0,
        "counter_speed":      8.5,
        "aerial_strength":    6.5,
        "style_code":         "AT",
        "travel_distance_km": 9500,
        "squad_morale":       9.5,   # defending champions
        "political_context":  "Reigning World Champions. Messi's final WC. Enormous motivation.",
        "political_risk":     0,
    },
    "Australia": {
        "coach":              "Tony Popovic",
        "formation":          "4-3-3",
        "key_xi":             ["Ryan", "Irankunda", "Leckie", "Metcalfe", "Irvine",
                               "Hrustic", "Rowles", "Souttar"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   +1.0,  # Irankunda breakthrough star (WC debut)
        "pressing_intensity": 7.5,
        "set_piece_threat":   6.5,
        "counter_speed":      8.0,   # Irankunda elite pace
        "aerial_strength":    7.0,
        "style_code":         "HP",
        "travel_distance_km": 14000,
        "squad_morale":       8.5,   # massive win vs Turkey lifted morale
        "political_context":  "Irankunda emerging as genuine star. Team belief sky-high after Turkey win.",
        "political_risk":     0,
    },
    "Turkey": {
        "coach":              "Vincenzo Montella",
        "formation":          "4-2-3-1",
        "key_xi":             ["Çakır", "Çalhanoğlu", "Arda Güler", "Kenan Yıldız",
                               "Yüksel", "Demiral", "Müldür"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   -0.5,  # morale hit after Australia loss
        "pressing_intensity": 7.0,
        "set_piece_threat":   6.5,
        "counter_speed":      7.0,
        "aerial_strength":    7.0,
        "style_code":         "AT",
        "travel_distance_km": 9000,
        "squad_morale":       6.0,   # dropped after 0-2 loss
        "political_context":  "Arda Güler talent but team underperformed vs Australia. Must respond.",
        "political_risk":     1,
    },

    # ══ Group E ══
    "Germany": {
        "coach":              "Julian Nagelsmann",
        "formation":          "4-2-3-1",
        "key_xi":             ["Neuer", "Kimmich", "Schlotterbeck", "Tah", "Raum",
                               "Gündoğan", "Andrich", "Musiala", "Wirtz", "Havertz", "Gnabry"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   +0.5,  # Wirtz + Musiala peak
        "pressing_intensity": 8.5,
        "set_piece_threat":   7.5,
        "counter_speed":      8.0,
        "aerial_strength":    7.5,
        "style_code":         "HP",
        "travel_distance_km": 7000,
        "squad_morale":       9.0,
        "political_context":  "Redemption after 2018 group exit. Wirtz era. High expectations.",
        "political_risk":     0,
    },
    "Curacao": {
        "coach":              "Remko Bicentini",
        "formation":          "4-4-2",
        "key_xi":             ["Virgil Misidjan", "Leandro Bacuna", "Cuco Martina",
                               "Rangelo Janga"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 5.0,
        "set_piece_threat":   5.0,
        "counter_speed":      5.5,
        "aerial_strength":    5.5,
        "style_code":         "DF",
        "travel_distance_km": 3500,
        "squad_morale":       7.5,   # first ever WC
        "political_context":  "Historic first WC. Small island nation with professional European-based players.",
        "political_risk":     0,
    },
    "Ivory Coast": {
        "coach":              "Emerse Faé",
        "formation":          "4-3-3",
        "key_xi":             ["Sangaré", "Haller", "Zaha", "Boga", "Pepe", "Konaté",
                               "Traoré", "Gradel"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 7.0,
        "set_piece_threat":   6.5,
        "counter_speed":      7.5,
        "aerial_strength":    7.0,
        "style_code":         "AT",
        "travel_distance_km": 9000,
        "squad_morale":       8.0,
        "political_context":  "AFCON 2024 holders. Experienced European-based squad.",
        "political_risk":     0,
    },
    "Ecuador": {
        "coach":              "Félix Sánchez",
        "formation":          "4-3-3",
        "key_xi":             ["Hernández", "Plata", "Valencia", "Cifuentes", "Preciado",
                               "Caicedo", "Sarmiento"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 6.5,
        "set_piece_threat":   6.0,
        "counter_speed":      6.5,
        "aerial_strength":    7.0,   # Enner Valencia aerial threat
        "style_code":         "AT",
        "travel_distance_km": 7000,
        "squad_morale":       7.5,
        "political_context":  "Young squad around Caicedo and Plata. Improving.",
        "political_risk":     0,
    },

    # ══ Group F ══
    "Brazil": {
        "coach":              "Dorival Júnior",
        "formation":          "4-2-3-1",
        "key_xi":             ["Alisson", "Danilo", "Militão", "Magalhães", "Wendell",
                               "Paquetá", "Bruno Guimarães", "Raphinha", "Rodrygo",
                               "Endrick", "Vinicius Jr."],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 7.5,
        "set_piece_threat":   7.0,
        "counter_speed":      9.0,   # Vinicius/Rodrygo/Endrick
        "aerial_strength":    7.0,
        "style_code":         "AT",
        "travel_distance_km": 8000,
        "squad_morale":       8.5,
        "political_context":  "Brazil craving first title since 2002. Enormous expectation.",
        "political_risk":     0,
    },
    "Morocco": {
        "coach":              "Walid Regragui",
        "formation":          "4-3-3",
        "key_xi":             ["Bono", "Hakimi", "Nayef Aguerd", "Saïss", "Masina",
                               "Ounahi", "Amrabat", "Ziyech", "En-Nesyri", "Boufal"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 7.5,
        "set_piece_threat":   7.0,
        "counter_speed":      8.0,
        "aerial_strength":    7.0,
        "style_code":         "CA",
        "travel_distance_km": 7000,
        "squad_morale":       9.0,   # 2022 semi-finalists
        "political_context":  "2022 semi-final heroes. Africa's best. Regragui tactics elite.",
        "political_risk":     0,
    },
    "Qatar": {
        "coach":              "Félix Sánchez",
        "formation":          "4-2-3-1",
        "key_xi":             ["Al-Sheeb", "Al-Rawi", "Hassan", "Ahmed Al-Hassan",
                               "Almoez Ali", "Akram Afif"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 6.5,
        "set_piece_threat":   5.5,
        "counter_speed":      6.5,
        "aerial_strength":    6.0,
        "style_code":         "CA",
        "travel_distance_km": 11000,
        "squad_morale":       6.5,
        "political_context":  "Asian Champions but global pressure + long travel.",
        "political_risk":     1,
    },
    "Switzerland": {
        "coach":              "Murat Yakin",
        "formation":          "3-4-3",
        "key_xi":             ["Sommer", "Elvedi", "Schär", "Akanji", "Shaqiri",
                               "Xhaka", "Freuler", "Vargas", "Embolo", "Ndoye"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 7.0,
        "set_piece_threat":   7.0,
        "counter_speed":      7.0,
        "aerial_strength":    7.0,
        "style_code":         "HP",
        "travel_distance_km": 7000,
        "squad_morale":       7.5,
        "political_context":  "Consistent overachievers. Xhaka leadership. Tactically flexible.",
        "political_risk":     0,
    },

    # ══ Group G ══
    "Portugal": {
        "coach":              "Roberto Martínez",
        "formation":          "4-3-3",
        "key_xi":             ["Costa", "Cancelo", "Pepe", "Dias", "Nuno Mendes",
                               "B.Silva", "Vitinha", "Fernandes", "Leão", "Ronaldo", "Félix"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   -0.3,  # Ronaldo declining but still dangerous
        "pressing_intensity": 7.0,
        "set_piece_threat":   8.0,
        "counter_speed":      8.5,
        "aerial_strength":    7.5,
        "style_code":         "AT",
        "travel_distance_km": 7500,
        "squad_morale":       8.5,
        "political_context":  "Ronaldo's last WC. Young talent around him. Heavy media focus.",
        "political_risk":     1,   # Ronaldo squad ego dynamics
    },
    "Italy": {
        "coach":              "Luciano Spalletti",
        "formation":          "4-3-3",
        "key_xi":             ["Donnarumma", "Di Lorenzo", "Bastoni", "Buongiorno", "Dimarco",
                               "Barella", "Jorginho", "Tonali", "Chiesa", "Retegui", "Raspadori"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 7.5,
        "set_piece_threat":   7.5,
        "counter_speed":      7.5,
        "aerial_strength":    7.0,
        "style_code":         "HP",
        "travel_distance_km": 7500,
        "squad_morale":       8.0,
        "political_context":  "EURO 2020 winners rebuilding. Spalletti pressing philosophy.",
        "political_risk":     0,
    },
    "Korea Republic": {
        "coach":              "Hong Myung-bo",
        "formation":          "4-2-3-1",
        "key_xi":             ["Kim Seung-gyu", "Kim Min-jae", "Hwang In-beom",
                               "Lee Kang-in", "Son Heung-min", "Hwang Hee-chan"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   +0.5,  # Son still in form, Lee Kang-in emerging
        "pressing_intensity": 7.5,
        "set_piece_threat":   6.5,
        "counter_speed":      8.0,
        "aerial_strength":    6.5,
        "style_code":         "HP",
        "travel_distance_km": 11000,
        "squad_morale":       8.5,   # win vs Czech Republic
        "political_context":  "Son carrying enormous expectations. Good team spirit.",
        "political_risk":     0,
    },
    "Czech Republic": {
        "coach":              "Ivan Hašek",
        "formation":          "4-2-3-1",
        "key_xi":             ["Vaclík", "Kuchta", "Schick", "Souček", "Hložek",
                               "Barák", "Coufal"],
        "injured":            ["Schick"],  # Patrik Schick ongoing fitness concerns
        "suspended":          [],
        "star_form_update":   -0.5,
        "pressing_intensity": 7.0,
        "set_piece_threat":   7.5,
        "counter_speed":      6.5,
        "aerial_strength":    7.5,
        "style_code":         "AT",
        "travel_distance_km": 8000,
        "squad_morale":       6.5,   # Schick injury uncertainty
        "political_context":  "Schick injury major concern. Compact but lacking cutting edge.",
        "political_risk":     0,
    },

    # ══ Group H ══
    "Netherlands": {
        "coach":              "Ronald Koeman",
        "formation":          "4-2-3-1",
        "key_xi":             ["Flekken", "Dumfries", "De Vrij", "Van Dijk", "Aké",
                               "Schouten", "Reijnders", "Gakpo", "Depay", "Xavi Simons", "Zirkzee"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   +0.3,
        "pressing_intensity": 7.5,
        "set_piece_threat":   7.5,
        "counter_speed":      8.0,
        "aerial_strength":    7.5,
        "style_code":         "AT",
        "travel_distance_km": 7000,
        "squad_morale":       8.5,
        "political_context":  "Van Dijk leadership. Gakpo and Simons in top form.",
        "political_risk":     0,
    },
    "Japan": {
        "coach":              "Hajime Moriyasu",
        "formation":          "4-2-3-1",
        "key_xi":             ["Gonda", "Tomiyasu", "Itakura", "Tanaka Ko", "Nagatomo",
                               "Morita", "Endo", "Kubo", "Minamino", "Ueda", "Kamada"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 8.5,
        "set_piece_threat":   6.5,
        "counter_speed":      8.5,
        "aerial_strength":    5.5,
        "style_code":         "HP",
        "travel_distance_km": 11000,
        "squad_morale":       8.5,
        "political_context":  "2022 QF. European-based squad. Elite high-press system.",
        "political_risk":     0,
    },
    "Sweden": {
        "coach":              "Jon Dahl Tomasson",
        "formation":          "4-4-2",
        "key_xi":             ["Olsen", "Lindelöf", "Granqvist", "Forsberg",
                               "Isak", "Gyökeres", "Kulusevski"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   +0.5,  # Isak & Gyökeres both elite form
        "pressing_intensity": 7.0,
        "set_piece_threat":   7.5,
        "counter_speed":      8.0,
        "aerial_strength":    8.0,
        "style_code":         "AT",
        "travel_distance_km": 7500,
        "squad_morale":       8.5,
        "political_context":  "Isak + Gyökeres = best striker pair in tournament. High expectations.",
        "political_risk":     0,
    },
    "Tunisia": {
        "coach":              "Jalel Kadri",
        "formation":          "4-3-3",
        "key_xi":             ["Dahmen", "Msakni", "Slimane", "Khenissi", "Laïdouni"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 6.0,
        "set_piece_threat":   6.0,
        "counter_speed":      6.5,
        "aerial_strength":    6.5,
        "style_code":         "DF",
        "travel_distance_km": 9000,
        "squad_morale":       7.0,
        "political_context":  "Defensively organised. Limited firepower outside Msakni.",
        "political_risk":     1,
    },

    # ══ Group I ══
    "England": {
        "coach":              "Thomas Tuchel",
        "formation":          "4-2-3-1",
        "key_xi":             ["Pickford", "Alexander-Arnold", "Stones", "Guehi", "Trippier",
                               "Rice", "Mainoo", "Bellingham", "Saka", "Foden", "Kane"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   +0.5,  # Bellingham Real Madrid form
        "pressing_intensity": 8.0,
        "set_piece_threat":   8.0,
        "counter_speed":      8.0,
        "aerial_strength":    7.5,
        "style_code":         "HP",
        "travel_distance_km": 7000,
        "squad_morale":       8.5,
        "political_context":  "Tuchel's pressing system new but players elite. Kane set-piece threat.",
        "political_risk":     0,
    },
    "Nigeria": {
        "coach":              "Augustine Eguavoen",
        "formation":          "4-3-3",
        "key_xi":             ["Uzoho", "Osimhen", "Lookman", "Ndidi", "Onyeka",
                               "Iheanacho", "Awoniyi"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   +0.5,  # Osimhen peak
        "pressing_intensity": 7.0,
        "set_piece_threat":   6.5,
        "counter_speed":      8.5,
        "aerial_strength":    7.5,
        "style_code":         "CA",
        "travel_distance_km": 9500,
        "squad_morale":       8.0,
        "political_context":  "Osimhen best African striker. Lookman in elite form too.",
        "political_risk":     1,
    },
    "Senegal": {
        "coach":              "Aliou Cissé",
        "formation":          "4-3-3",
        "key_xi":             ["Mendy", "Diatta", "Koulibaly", "Diallo", "Ismaïla Sarr",
                               "Gueye", "Nampalys Mendy", "Mané"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   -0.3,  # Mané still recovering from previous injury
        "pressing_intensity": 7.0,
        "set_piece_threat":   7.0,
        "counter_speed":      8.0,
        "aerial_strength":    7.5,
        "style_code":         "AT",
        "travel_distance_km": 7500,
        "squad_morale":       8.5,
        "political_context":  "AFCON 2021/22 winners. Koulibaly leadership. Africa's top side.",
        "political_risk":     0,
    },
    "Iran": {
        "coach":              "Amir Ghalenoei",
        "formation":          "4-2-3-1",
        "key_xi":             ["Beiranvand", "Jahanbakhsh", "Taremi", "Cheshmi",
                               "Rezaeian", "Ebrahimi"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 6.0,
        "set_piece_threat":   5.5,
        "counter_speed":      6.5,
        "aerial_strength":    6.5,
        "style_code":         "DF",
        "travel_distance_km": 12000,
        "squad_morale":       5.0,   # political tensions
        "political_context":  "Political instability at home affecting team focus. Long travel.",
        "political_risk":     4,    # significant political risk factor
    },

    # ══ Group J ══
    "Uruguay": {
        "coach":              "Marcelo Bielsa",
        "formation":          "4-3-3",
        "key_xi":             ["Rochet", "Varela", "Giménez", "Araújo", "Olivera",
                               "Ugarte", "Bentancur", "Pellistri", "Valverde", "Darwin Núñez", "Cavani"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   +0.5,  # Valverde + Núñez elite form
        "pressing_intensity": 8.5,   # Bielsa high-press
        "set_piece_threat":   7.0,
        "counter_speed":      8.5,
        "aerial_strength":    7.5,
        "style_code":         "HP",
        "travel_distance_km": 9000,
        "squad_morale":       9.0,
        "political_context":  "Bielsa's pressing philosophy. Valverde + Núñez in career-best form.",
        "political_risk":     0,
    },
    "Saudi Arabia": {
        "coach":              "Roberto Mancini",
        "formation":          "4-2-3-1",
        "key_xi":             ["Al-Owais", "Al-Amri", "Al-Bulayhi", "Salem Al-Dawsari",
                               "Firas Al-Buraikan", "Sami Al-Najei"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 7.0,
        "set_piece_threat":   6.0,
        "counter_speed":      7.0,
        "aerial_strength":    6.5,
        "style_code":         "CA",
        "travel_distance_km": 13000,
        "squad_morale":       7.5,
        "political_context":  "Mancini coaching. Al-Dawsari key player. Government funding.",
        "political_risk":     0,
    },
    "Venezuela": {
        "coach":              "Fernando Batista",
        "formation":          "4-4-2",
        "key_xi":             ["Romo", "Soteldo", "Machís", "Flores", "Herrera",
                               "Murillo", "Savarino"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 6.5,
        "set_piece_threat":   5.5,
        "counter_speed":      7.0,
        "aerial_strength":    6.0,
        "style_code":         "CA",
        "travel_distance_km": 4500,
        "squad_morale":       9.0,   # historic first WC
        "political_context":  "First ever WC — massive national pride. Soteldo class act.",
        "political_risk":     2,
    },
    "New Zealand": {
        "coach":              "Darren Bazeley",
        "formation":          "4-4-2",
        "key_xi":             ["Sail", "Garbett", "Thomas", "Wood", "McGlinchey"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 5.5,
        "set_piece_threat":   5.5,
        "counter_speed":      5.5,
        "aerial_strength":    6.5,
        "style_code":         "DF",
        "travel_distance_km": 13000,
        "squad_morale":       7.0,
        "political_context":  "Compact and disciplined but major quality gap to top sides.",
        "political_risk":     0,
    },

    # ══ Group K ══
    "Canada": {
        "coach":              "Jesse Marsch",
        "formation":          "4-3-3",
        "key_xi":             ["Borjan", "Johnston", "Vitória", "Henry", "Laryea",
                               "Hoilett", "Eustáquio", "Hutchinson", "David", "Davies", "Buchanan"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 8.0,
        "set_piece_threat":   6.5,
        "counter_speed":      9.0,   # Davies top-5 in world for pace
        "aerial_strength":    7.0,
        "style_code":         "HP",
        "travel_distance_km": 0,     # co-host
        "squad_morale":       8.5,
        "political_context":  "Co-host. Davies elite pace but team can stall without him in form.",
        "political_risk":     0,
    },
    "Bosnia and Herzegovina": {
        "coach":              "Sergej Barbarez",
        "formation":          "4-2-3-1",
        "key_xi":             ["Kovačević", "Džeko", "Pjanic", "Hajradinović", "Kolasinac",
                               "Ahmedhodzic", "Gojak"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   -0.3,  # Džeko ageing
        "pressing_intensity": 6.5,
        "set_piece_threat":   7.0,
        "counter_speed":      6.5,
        "aerial_strength":    8.0,   # Džeko aerial threat
        "style_code":         "AT",
        "travel_distance_km": 8500,
        "squad_morale":       8.0,
        "political_context":  "First WC. Pjanic and Džeko veterans. Unified despite complex politics.",
        "political_risk":     1,
    },
    "Colombia": {
        "coach":              "Néstor Lorenzo",
        "formation":          "4-2-3-1",
        "key_xi":             ["Vargas", "Muñoz", "Mina", "Sánchez", "Mojica",
                               "Lerma", "Arias", "James Rodríguez", "Díaz", "Ríos", "Córdoba"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   +0.5,  # James + Diaz both in form
        "pressing_intensity": 7.0,
        "set_piece_threat":   6.5,
        "counter_speed":      7.5,
        "aerial_strength":    7.0,
        "style_code":         "CA",
        "travel_distance_km": 4500,
        "squad_morale":       8.5,
        "political_context":  "Copa América finalists. James Rodriguez still influential.",
        "political_risk":     0,
    },
    "Iraq": {
        "coach":              "Jesús Casas",
        "formation":          "4-3-3",
        "key_xi":             ["Bashar Resan", "Aymen Hussein", "Amjad Attwan",
                               "Mohanad Ali"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 5.5,
        "set_piece_threat":   5.5,
        "counter_speed":      6.0,
        "aerial_strength":    6.5,
        "style_code":         "DF",
        "travel_distance_km": 12500,
        "squad_morale":       7.0,
        "political_context":  "Historic qualification. Political tensions at home.",
        "political_risk":     3,
    },

    # ══ Group L ══
    "Scotland": {
        "coach":              "Steve Clarke",
        "formation":          "3-5-2",
        "key_xi":             ["Gunn", "Hendry", "Hanley", "Cooper", "McGinn",
                               "McGregor", "Gilmour", "Adams", "Christie", "Dykes"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   +0.3,  # McGinn goal vs Haiti lifted mood
        "pressing_intensity": 7.5,
        "set_piece_threat":   7.0,
        "counter_speed":      6.5,
        "aerial_strength":    7.5,
        "style_code":         "HP",
        "travel_distance_km": 6500,
        "squad_morale":       8.0,
        "political_context":  "McGinn the heartbeat. Compact and hard-working under Clarke.",
        "political_risk":     0,
    },
    "Haiti": {
        "coach":              "Marc Collat",
        "formation":          "4-4-2",
        "key_xi":             ["Josue Duverger", "Duckens Nazon", "Wilde-Donald Guerrier",
                               "James Léandro"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 5.5,
        "set_piece_threat":   5.0,
        "counter_speed":      6.5,
        "aerial_strength":    6.0,
        "style_code":         "CA",
        "travel_distance_km": 2500,
        "squad_morale":       5.5,   # political chaos at home
        "political_context":  "Political crisis at home severely impacts squad morale and logistics.",
        "political_risk":     8,    # Haiti political instability is severe
    },
    "Kazakhstan": {
        "coach":              "Magomed Adiev",
        "formation":          "4-4-2",
        "key_xi":             ["Pokatilov", "Zaynutdinov", "Vorogovskiy", "Shchetkin",
                               "Aymbetov"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   0.0,
        "pressing_intensity": 5.5,
        "set_piece_threat":   5.5,
        "counter_speed":      5.5,
        "aerial_strength":    6.5,
        "style_code":         "DF",
        "travel_distance_km": 12000,
        "squad_morale":       7.5,
        "political_context":  "Surprising qualifiers. United by underdog spirit. Long travel.",
        "political_risk":     0,
    },
    "Nigeria": {  # duplicate key handled gracefully — keep the one above
        "coach":              "Augustine Eguavoen",
        "formation":          "4-3-3",
        "key_xi":             ["Uzoho", "Osimhen", "Lookman", "Ndidi", "Onyeka",
                               "Iheanacho", "Awoniyi"],
        "injured":            [],
        "suspended":          [],
        "star_form_update":   +0.5,
        "pressing_intensity": 7.0,
        "set_piece_threat":   6.5,
        "counter_speed":      8.5,
        "aerial_strength":    7.5,
        "style_code":         "CA",
        "travel_distance_km": 9500,
        "squad_morale":       8.0,
        "political_context":  "Osimhen best African striker. Lookman in elite form too.",
        "political_risk":     1,
    },
}

# ── Teams not in individual groups above — fill defaults ──────────────────────
_DEFAULT = {
    "coach":              "Unknown",
    "formation":          "4-4-2",
    "key_xi":             [],
    "injured":            [],
    "suspended":          [],
    "star_form_update":   0.0,
    "pressing_intensity": 6.0,
    "set_piece_threat":   6.0,
    "counter_speed":      6.0,
    "aerial_strength":    6.5,
    "style_code":         "CA",
    "travel_distance_km": 10000,
    "squad_morale":       7.0,
    "political_context":  "No specific context available.",
    "political_risk":     0,
}


# ── Star player bios — WHY they carry their team ─────────────────────────────
# club_achievement = biggest recent trophy/feat
# season_stats     = key 2024-25 club season numbers
# why_carrying     = plain English reason why team collapses without them
# fatigue_level    = 0 (fresh) – 10 (exhausted), based on club season load
# injury_risk      = 0 (fully fit) – 10 (major doubt)
STAR_PLAYERS: dict[str, dict] = {
    "United States": {
        "name":             "Christian Pulisic",
        "club":             "AC Milan",
        "club_achievement": "Serie A campaign, consistent form at Milan",
        "season_stats":     "12 goals, 8 assists in Serie A 2024-25",
        "why_carrying":     "Only USMNT player who can create chances from nothing. When he drifts inside from the left, USA's attack comes alive. Without him they become predictable and slow.",
        "fatigue_level":    4,
        "injury_risk":      3,
    },
    "Spain": {
        "name":             "Lamine Yamal",
        "club":             "FC Barcelona",
        "club_achievement": "EURO 2024 winner at age 17 — youngest ever scorer in Euros",
        "season_stats":     "20+ goals, 18 assists in La Liga 2024-25 (age 17)",
        "why_carrying":     "Once-in-a-generation talent. His dribbling and vision at 17 are unprecedented. Spain's right side is unplayable when he's at his best — defenders don't know whether to track him or stay.",
        "fatigue_level":    3,
        "injury_risk":      2,
    },
    "France": {
        "name":             "Kylian Mbappé",
        "club":             "Real Madrid",
        "club_achievement": "Champions League winner 2024 with Real Madrid, La Liga champion",
        "season_stats":     "35 goals across all competitions in first Real Madrid season",
        "why_carrying":     "Fastest striker at the tournament. Real Madrid's big-game mentality rubbed off — he now performs in finals, not just group stages. Without him, France lose their only genuine 1v1 threat.",
        "fatigue_level":    5,
        "injury_risk":      2,
    },
    "Argentina": {
        "name":             "Lionel Messi",
        "club":             "Inter Miami",
        "club_achievement": "2022 World Cup winner — fulfilled destiny. Copa América 2021 winner.",
        "season_stats":     "MLS regular season 2024: 20 goals, 16 assists at age 37",
        "why_carrying":     "Still the most intelligent player on any field. His pressing resistance, passing angles, and set-piece delivery are irreplaceable. Argentina without Messi is a good team; with him they're potentially the greatest team ever assembled.",
        "fatigue_level":    6,  # MLS is less intense but age is a factor
        "injury_risk":      4,
    },
    "Brazil": {
        "name":             "Vinícius Júnior",
        "club":             "Real Madrid",
        "club_achievement": "Champions League winner 2024, Ballon d'Or runner-up, La Liga champion",
        "season_stats":     "24 goals, 11 assists in La Liga 2024-25 — best season to date",
        "why_carrying":     "The only player in Brazil's squad who can single-handedly change a game. His pace, dribbling and direct running at goal is world-class. When Vini goes cold, Brazil become toothless despite their other attacking options.",
        "fatigue_level":    5,
        "injury_risk":      3,
    },
    "Morocco": {
        "name":             "Achraf Hakimi",
        "club":             "Paris Saint-Germain",
        "club_achievement": "Ligue 1 champion 2024-25 with PSG, Champions League semi-finalist",
        "season_stats":     "9 goals, 14 assists from right-back — best season in career",
        "why_carrying":     "The most attacking right-back in world football. His overlapping runs create a 2v1 overload every time. Morocco's entire right flank is built around his engine — without him, Regragui's system loses its most dangerous weapon.",
        "fatigue_level":    6,
        "injury_risk":      2,
    },
    "Germany": {
        "name":             "Florian Wirtz",
        "club":             "Bayer Leverkusen",
        "club_achievement": "Bundesliga Unbeaten Champion 2023-24 with Leverkusen (51-game unbeaten run)",
        "season_stats":     "18 goals, 20 assists in Bundesliga 2024-25",
        "why_carrying":     "The most creative player in the Bundesliga for two seasons running. His one-touch combinations in tight spaces, through-balls and late runs into the box make Germany's midfield impossible to press. Germany's fluid system falls apart if he's man-marked out of the game.",
        "fatigue_level":    4,
        "injury_risk":      2,
    },
    "Portugal": {
        "name":             "Cristiano Ronaldo",
        "club":             "Al Nassr",
        "club_achievement": "Arab Champions Cup, 850+ career goals — most in history",
        "season_stats":     "35 goals in Saudi Pro League 2024-25 (but lower competition level)",
        "why_carrying":     "At 41, he's no longer a true world-class player but his leadership, aerial threat, and penalty box presence are still elite. Portuguese players visibly raise their game around him. The psychological weight of Ronaldo on the opposition is real — but so is the question of whether his pace decline exposes them.",
        "fatigue_level":    5,
        "injury_risk":      3,
    },
    "England": {
        "name":             "Jude Bellingham",
        "club":             "Real Madrid",
        "club_achievement": "Champions League winner 2024 with Real Madrid, La Liga champion",
        "season_stats":     "23 goals, 13 assists from midfield in 2024-25 — one of the best in world",
        "why_carrying":     "Plays like a midfielder, scores like a striker. Real Madrid's biggest matches brought out his best — he's now proven he can perform at the highest level. England's attack goes through him: runs beyond, holds up, scores. Without Bellingham, England are a decent defensive team with no creativity.",
        "fatigue_level":    5,
        "injury_risk":      2,
    },
    "Netherlands": {
        "name":             "Virgil van Dijk",
        "club":             "Liverpool",
        "club_achievement": "Premier League champion 2024-25 with Liverpool",
        "season_stats":     "Captain of PL-winning Liverpool — dominant all season",
        "why_carrying":     "The most commanding centre-back at the tournament. His reading of the game, leadership and aerial dominance organise the entire Dutch defensive shape. When Van Dijk is on form, the Netherlands concede almost nothing. Without him, their defence is chaotic.",
        "fatigue_level":    4,
        "injury_risk":      2,
    },
    "Italy": {
        "name":             "Nicolò Barella",
        "club":             "Inter Milan",
        "club_achievement": "Serie A champion 2023-24 with Inter, Champions League finalist",
        "season_stats":     "10 goals, 15 assists in all competitions 2024-25",
        "why_carrying":     "Italy's engine. He covers every blade of grass, wins the ball back and immediately starts attacks. Spalletti's 4-3-3 pressing system relies on Barella's tireless work rate to make the press work. If he's tired or off-form, Italy's entire pressing structure collapses.",
        "fatigue_level":    5,
        "injury_risk":      2,
    },
    "Korea Republic": {
        "name":             "Son Heung-min",
        "club":             "Tottenham Hotspur",
        "club_achievement": "PL top scorer campaigns, 100+ Premier League goals",
        "season_stats":     "18 goals, 10 assists in PL 2024-25",
        "why_carrying":     "The entire Korean attack is designed to find Son in space on the left. His finishing, pace off the left and ability to cut inside make him genuinely dangerous against any defence. Korea's xG without Son on form is roughly half of what it is with him.",
        "fatigue_level":    5,
        "injury_risk":      3,
    },
    "Japan": {
        "name":             "Takefusa Kubo",
        "club":             "Real Sociedad",
        "club_achievement": "Consistent performer in La Liga — best Asian player in Spain",
        "season_stats":     "14 goals, 10 assists in La Liga 2024-25",
        "why_carrying":     "The most technically gifted player in Japan's squad. His dribbling in tight spaces, ability to beat men and shoot from distance are elite. Japan's high-press system is tactical, but Kubo is the individual difference-maker who turns structure into goals.",
        "fatigue_level":    4,
        "injury_risk":      2,
    },
    "Australia": {
        "name":             "Nestory Irankunda",
        "club":             "Bayern Munich",
        "club_achievement": "Bundesliga champion 2024-25 with Bayern — youngest ever in team history",
        "season_stats":     "8 goals, 6 assists off the bench at Bayern — historic debut season",
        "why_carrying":     "17-year-old phenom who already scored on WC debut vs Turkey. Pure pace and directness — defenders cannot contain him 1v1. Australia's attack has never had a player of this calibre before. He's the reason expectations have dramatically shifted.",
        "fatigue_level":    2,  # young, fresh
        "injury_risk":      1,
    },
    "Uruguay": {
        "name":             "Federico Valverde",
        "club":             "Real Madrid",
        "club_achievement": "Champions League winner 2024 with Real Madrid, La Liga champion",
        "season_stats":     "12 goals, 10 assists from box-to-box midfield role 2024-25",
        "why_carrying":     "The complete midfielder. Can press, score, assist, defend, and run all 90 minutes. Under Bielsa's high-press system, Valverde is the player who makes the press actually work — his engine allows Uruguay to press 90 minutes without dropping intensity.",
        "fatigue_level":    5,
        "injury_risk":      2,
    },
    "Belgium": {
        "name":             "Kevin De Bruyne",
        "club":             "Manchester City",
        "club_achievement": "Premier League champion multiple times, Champions League winner 2023",
        "season_stats":     "8 goals, 14 assists in PL 2024-25 (returned from long injury layoff)",
        "why_carrying":     "When fit, the best passing midfielder on the planet. But his injury record is now the biggest question mark. Belgium's entire creative output relies on De Bruyne's vision. Without him they have Doku's pace but no one to find him in space.",
        "fatigue_level":    7,  # coming back from injuries
        "injury_risk":      5,
    },
    "Egypt": {
        "name":             "Mohamed Salah",
        "club":             "Liverpool",
        "club_achievement": "Premier League champion 2024-25 with Liverpool, PL Golden Boot",
        "season_stats":     "28 goals, 17 assists in PL 2024-25 — best season of career at age 32",
        "why_carrying":     "In the form of his life. Won PL with Liverpool this season, scored more than ever. Egypt's attack is essentially Salah plus 10 players trying to find him. If opposition shuts him down, Egypt have no Plan B — but shutting down Salah right now is nearly impossible.",
        "fatigue_level":    6,  # long PL season
        "injury_risk":      2,
    },
    "Senegal": {
        "name":             "Sadio Mané",
        "club":             "Al Nassr",
        "club_achievement": "AFCON winner 2021-22 with Senegal, Premier League & CL winner (Liverpool era)",
        "season_stats":     "22 goals in Saudi Pro League 2024-25",
        "why_carrying":     "Still Senegal's most dangerous attacker despite Saudi move. His intensity, work rate and finishing in big moments are unmatched in the squad. Senegal without Mané are competent; with him at full fitness they're a genuine last-8 threat.",
        "fatigue_level":    5,
        "injury_risk":      4,  # history of hamstring issues
    },
    "Colombia": {
        "name":             "James Rodríguez",
        "club":             "Rayo Vallecano",
        "club_achievement": "Copa América finalist 2024, FIFA WC 2014 Golden Boot (his prime)",
        "season_stats":     "11 goals, 13 assists in La Liga 2024-25 — career revival at Rayo",
        "why_carrying":     "Shocking career revival at Rayo Vallecano after failed Saudi spell. Still has the best left foot in South America — his range of passing, dribbles into the box and set-piece delivery are world-class. Colombia discovered a new attacking identity with him pulling the strings.",
        "fatigue_level":    4,
        "injury_risk":      3,
    },
    "Nigeria": {
        "name":             "Victor Osimhen",
        "club":             "Galatasaray",
        "club_achievement": "Süper Lig champion 2024-25, top scorer in Turkish league",
        "season_stats":     "32 goals, 8 assists in Süper Lig 2024-25 — dominant season",
        "why_carrying":     "The most dangerous No.9 in Africa. His pace, physicality and clinical finishing make him a nightmare for any defence. Nigeria's entire attacking plan is: get the ball to Osimhen as quickly as possible. He carries Nigeria so much that even mediocre service turns into goals.",
        "fatigue_level":    4,
        "injury_risk":      2,
    },
    "Sweden": {
        "name":             "Alexander Isak",
        "club":             "Newcastle United",
        "club_achievement": "Consistent top-10 PL scorer, Champions League regular with Newcastle",
        "season_stats":     "26 goals in PL 2024-25 — top-5 scorer in England",
        "why_carrying":     "The complete modern striker. Dribbles like a winger, scores like a classic No.9, holds up play and brings teammates in. Sweden have never had a striker of this quality. Isak + Gyökeres = the most frightening strike partnership at the tournament.",
        "fatigue_level":    4,
        "injury_risk":      3,
    },
    "Canada": {
        "name":             "Alphonso Davies",
        "club":             "Bayern Munich",
        "club_achievement": "Bundesliga champion 2024-25 with Bayern",
        "season_stats":     "7 goals, 12 assists from left-back — best attacking output yet",
        "why_carrying":     "The fastest player at the tournament. When Davies gets the ball in wide areas with space, he's uncontrollable. Co-host pressure is huge — the entire Canadian public knows his name. The weight of expectation is enormous.",
        "fatigue_level":    5,
        "injury_risk":      3,
    },
    "Mexico": {
        "name":             "Hirving 'Chucky' Lozano",
        "club":             "Guadalajara (Chivas)",
        "club_achievement": "Liga MX champion 2024-25, El Tri captain",
        "season_stats":     "18 goals, 10 assists in Liga MX — top scorer",
        "why_carrying":     "Returned to Mexico after Europe — emotional captain. His pace on the counter and directness give Mexico an outlet their possession struggles create. The co-host crowd chants his name. But El Tri's performances historically depend on Lozano's individual brilliance.",
        "fatigue_level":    4,
        "injury_risk":      3,
    },
    "Scotland": {
        "name":             "John McGinn",
        "club":             "Aston Villa",
        "club_achievement": "Champions League regular with Aston Villa 2024-25, Europa League",
        "season_stats":     "12 goals, 8 assists in all competitions for Villa 2024-25",
        "why_carrying":     "Scotland's heartbeat. His box-to-box energy, goalscoring from midfield and leadership set the team's tempo. Already scored in this WC (vs Haiti). Without his pressing and goal threat, Scotland become predictable and lack any creativity.",
        "fatigue_level":    4,
        "injury_risk":      2,
    },
    "Switzerland": {
        "name":             "Granit Xhaka",
        "club":             "Bayer Leverkusen",
        "club_achievement": "Bundesliga Unbeaten Champion 2023-24 with Leverkusen, DFB-Pokal winner",
        "season_stats":     "8 goals, 14 assists — best season of career at 31",
        "why_carrying":     "Transformed at Leverkusen. No longer the player who gave away penalties at Arsenal — now a deep-lying playmaker who won the Bundesliga unbeaten. His range of passing and leadership organise Switzerland's entire shape. Switzerland without Xhaka are compact but toothless.",
        "fatigue_level":    5,
        "injury_risk":      2,
    },
    "Qatar": {
        "name":             "Akram Afif",
        "club":             "Al-Sadd",
        "club_achievement": "AFC Champions League winner, Asian Cup 2023 Golden Ball winner",
        "season_stats":     "21 goals in Qatar Stars League 2024-25",
        "why_carrying":     "Asian Cup's best player in 2023. The only Qatar player who can create something from nothing against top opposition. Without Afif's dribbling and through-balls, Qatar become completely predictable in attack.",
        "fatigue_level":    3,
        "injury_risk":      2,
    },
    "Turkey": {
        "name":             "Arda Güler",
        "club":             "Real Madrid",
        "club_achievement": "Champions League winner 2024 with Real Madrid, La Liga champion",
        "season_stats":     "11 goals, 8 assists in La Liga 2024-25 off the bench — Ancelotti's wildcard",
        "why_carrying":     "Superstar in waiting. Ancelotti kept him as a weapon off the bench — that means he's electric in short bursts. Turkey's entire attacking identity is built around giving Güler the ball in the final third and letting him improvise. After the Australia loss, he needs to step up.",
        "fatigue_level":    3,
        "injury_risk":      2,
    },
    "Iran": {
        "name":             "Mehdi Taremi",
        "club":             "Inter Milan",
        "club_achievement": "Serie A champion 2023-24 with Inter, Champions League finalist",
        "season_stats":     "14 goals in all competitions for Inter 2024-25",
        "why_carrying":     "The only Iran player in a genuine elite European club. His hold-up play, link-up and clinical finishing inside the box are world-class. Iran without Taremi scoring have historically never beaten major opposition.",
        "fatigue_level":    5,
        "injury_risk":      3,
    },
    "Saudi Arabia": {
        "name":             "Salem Al-Dawsari",
        "club":             "Al-Hilal",
        "club_achievement": "Asian Champions League winner, Saudi Pro League champion",
        "season_stats":     "20 goals, 12 assists in Saudi Pro League 2024-25",
        "why_carrying":     "The man who scored the goal that shocked Argentina in 2022. National hero. His left-footed curling shots and ability to beat defenders 1v1 from the right are Saudi Arabia's best weapon. He IS Saudi football.",
        "fatigue_level":    4,
        "injury_risk":      2,
    },
    "Serbia": {
        "name":             "Dušan Vlahović",
        "club":             "Juventus",
        "club_achievement": "Serie A top-5 scorer for Juventus, consistent European performer",
        "season_stats":     "22 goals in Serie A 2024-25",
        "why_carrying":     "One of the most technically complete strikers in Europe at 24. His combination of aerial dominance, powerful shooting and hold-up play terrorise any defence. Serbia's entire set-piece strategy is built around getting the ball to Vlahović's head.",
        "fatigue_level":    4,
        "injury_risk":      2,
    },
    "Portugal": {
        "name":             "Cristiano Ronaldo",
        "club":             "Al Nassr",
        "club_achievement": "850+ career goals — most ever in football history",
        "season_stats":     "35 goals in Saudi Pro League 2024-25 at age 39",
        "why_carrying":     "It's Ronaldo. Even at 39, his leadership, set-piece accuracy and penalty box presence are elite. Portugal play differently when he's on — more direct, more aerial balls, more pressure on the opponent. The real question is whether his pace decline creates defensive issues for the team.",
        "fatigue_level":    5,
        "injury_risk":      3,
    },
    "Bosnia and Herzegovina": {
        "name":             "Edin Džeko",
        "club":             "Fenerbahçe",
        "club_achievement": "Süper Lig golden years with Fenerbahçe, record Bosnia scorer",
        "season_stats":     "16 goals in Süper Lig 2024-25 at age 38",
        "why_carrying":     "The greatest player in Bosnian history. Even at 38, his hold-up play, aerial ability and link-up with Vlahović-type partners is elite. Bosnia's first ever WC is partly because of him. Carries the hopes of an entire nation.",
        "fatigue_level":    6,
        "injury_risk":      4,
    },
    "Uruguay": {
        "name":             "Federico Valverde",
        "club":             "Real Madrid",
        "club_achievement": "Champions League winner 2024, La Liga champion",
        "season_stats":     "12 goals, 10 assists from midfield in 2024-25",
        "why_carrying":     "Redefining what a midfielder can do. Box-to-box but also goal-scoring, pressing-machine and tactical intelligence. Bielsa's system needs a Valverde-type engine to function — without him, the high-press becomes a high-risk.",
        "fatigue_level":    5,
        "injury_risk":      2,
    },
}

# ── Yellow card tracker — current WC 2026 bookings ──────────────────────────
# Format: {team: {player_name: yellow_count}}
# 2026 NEW RULE: Yellow cards are reset after the GROUP STAGE (not after R16).
# This means group stage yellows do NOT carry into the Round of 32.
# Within each knockout round, 2 yellows in the same round = 1-match ban.
# Cards then reset again after the Quarter-Finals.
# ⚠️  Only flag a player as "suspended" if they have 2 yellows in the SAME stage.
YELLOW_CARDS: dict[str, dict[str, int]] = {
    # Group A
    "United States":  {},
    "Panama":         {},
    "Honduras":       {},
    "Jamaica":        {},
    # Group B
    "Spain":          {},
    "Cabo Verde":     {},
    "Belgium":        {},
    "Egypt":          {},
    # Group C
    "Mexico":         {},
    "South Africa":   {},
    "Serbia":         {},
    "Costa Rica":     {},
    # Group D
    "France":         {},
    "Argentina":      {},
    "Australia":      {"Souttar": 1},
    "Turkey":         {"Demiral": 1, "Müldür": 1},
    # Group E
    "Germany":        {},
    "Curacao":        {},
    "Ivory Coast":    {},
    "Ecuador":        {},
    # Group F
    "Brazil":         {"Danilo": 1},
    "Morocco":        {"Amrabat": 1},
    "Qatar":          {},
    "Switzerland":    {},
    # Group G
    "Portugal":       {},
    "Italy":          {},
    "Korea Republic": {"Kim Min-jae": 1},
    "Czech Republic": {"Souček": 1},
    # Group H
    "Netherlands":    {},
    "Japan":          {},
    "Sweden":         {},
    "Tunisia":        {},
    # Group I
    "England":        {},
    "Nigeria":        {},
    "Senegal":        {},
    "Iran":           {},
    # Group J
    "Uruguay":        {},
    "Saudi Arabia":   {},
    "Venezuela":      {},
    "New Zealand":    {},
    # Group K
    "Canada":         {"Johnston": 1},
    "Bosnia and Herzegovina": {"Kolasinac": 1},
    "Colombia":       {},
    "Iraq":           {},
    # Group L
    "Scotland":       {},
    "Haiti":          {},
    "Kazakhstan":     {},
}


def get_player_data(team: str) -> dict:
    """Return player data for a team, falling back to defaults for missing teams."""
    d = _DEFAULT.copy()
    d.update(PLAYER_DATA.get(team, {}))
    d["star_player"]  = STAR_PLAYERS.get(team, {})
    d["yellow_cards"] = YELLOW_CARDS.get(team, {})
    return d


if __name__ == "__main__":
    import pandas as pd
    rows = []
    for team, d in PLAYER_DATA.items():
        rows.append({
            "team":     team,
            "coach":    d.get("coach",""),
            "form":     d.get("formation",""),
            "injured":  ", ".join(d.get("injured",[])) or "—",
            "morale":   d.get("squad_morale", 7),
            "press":    d.get("pressing_intensity", 6),
            "pol_risk": d.get("political_risk", 0),
        })
    df = pd.DataFrame(rows)
    print(df.to_string(index=False))
